apiVersion: v1
kind: ConfigMap
metadata:
  name: be-network-importer-config
data:
  application-embedd.yaml: |
    logging:
      level:
        org.springframework: INFO
        org.hibernate.SQL: INFO
        org.hibernate.type: WARN
    
    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          show-details: 'always'
      server:
        port: 9081
    
    spring:
      liquibase:
        enabled: false      
      application:
        name: be-network-importer
      jackson:
        property-naming-strategy: SNAKE_CASE
        serialization:
          write-dates-as-timestamps: 'false'
    
      jpa:
        open-in-view: false
        database-platform: postgres
        properties:
          hibernate:
            boot:
              allow_jdbc_metadata_access: false
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: data
            jdbc.time_zone: UTC
        show-sql: false
    
      datasource:
        driver-class-name: org.postgresql.Driver      
        url: jdbc:postgresql://db.donista-production:5432/postgres
        username: postgres
        password: 'nope'
    
    server:
      port: 8080
    
    db-scheduler:
      threads: 5
      polling-interval: 5s
      immediate-execution-enabled: true
      table-name: tasks.scheduled_tasks
      polling-strategy: fetch
      polling-strategy-lower-limit-fraction-of-threads: 0.5
      polling-strategy-upper-limit-fraction-of-threads: 3.0
      shutdown-max-wait: 30m
      always-persist-timestamp-in-utc: true
    
    db-scheduler-log:
      enabled: true
      table-name: tasks.scheduled_execution_logs
    
    db-scheduler-ui:
      history: true
      log-limit: 1000
      
