apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-network-importer
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be-network-importer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be-network-importer
    spec:
      serviceAccountName: be-network-importer-ksa
      containers:
        - name: be-network-importer
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 5
            successThreshold: 1
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 5005
            name: debug
          - containerPort: 9081
            name: metrics
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
          volumeMounts:
            - mountPath: /config
              name: config-vol
      volumes:
        - name: config-vol
          configMap:
            name: be-network-importer-config

